# Generated by Django 5.2.15 on 2026-06-11 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='session_materials/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='study_sessions.session')),
            ],
            options={
                'verbose_name': 'Material de Sesión',
                'verbose_name_plural': 'Materiales de Sesión',
            },
        ),
    ]
