# Generated by Django 5.2.15 on 2026-06-11 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Explica qué necesitas aprender o qué falta.')),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('FULFILLED', 'Resuelta'), ('REJECTED', 'Rechazada')], default='PENDING', max_length=20)),
                ('admin_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_requests', to='users.student')),
            ],
            options={
                'verbose_name': 'Solicitud de Materia',
                'verbose_name_plural': 'Solicitudes de Materias',
                'ordering': ['-created_at'],
            },
        ),
    ]
