# Generated by Django 5.2.15 on 2026-06-12 02:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subjectrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrequest',
            name='proposed_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Lo que el estudiante está dispuesto a pagar por 1 hora.', max_digits=10),
        ),
        migrations.AddField(
            model_name='subjectrequest',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='subjectrequest',
            name='description',
            field=models.TextField(help_text='Detalle del tema que quieres ver en la clase.'),
        ),
        migrations.AlterField(
            model_name='subjectrequest',
            name='subject_name',
            field=models.CharField(help_text='Nombre si la materia no está en la lista', max_length=100),
        ),
    ]
