# Generated by Django 5.2.15 on 2026-06-15 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_subjectrequest_proposed_price_subjectrequest_subject_and_more'),
        ('tutors', '0002_alter_tutor_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectrequest',
            name='accepted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_requests', to='tutors.tutor'),
        ),
        migrations.AddField(
            model_name='subjectrequest',
            name='preferred_datetime',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora sugerida por el alumno.', null=True),
        ),
    ]
