# Generated by Django 5.2.15 on 2026-06-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
